all:
  hosts:
    0.0.0.0:
  vars:
    ansible_ssh_user: 'root'
    ansible_port: '22'

    TRAEFIK_DOMAIN: traefik.gql.treeton.localhost
    TRAEFIL_ACME_EMAIL: traefik@gql.treeton.localhost
    TRAEFIK_METRICS_DOMAIN: metrics.traefik.gql.treeton.localhost
    TEMPO_DOMAIN: tempo.gql.treeton.localhost
    ARANGO_DOMAIN: arango.gql.treeton.localhost
    STATSD_DOMAIN: statsd.gql.treeton.localhost
    Q_SERVER_DOMAIN: gql.treeton.localhost

    ARANGO_ROOT_PASSWORD: 123
    ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY: 32G

    EVER_NODE_CONSOLE_SERVER_PORT: 3031
    EVER_NODE_VALIDATOR_NAME: KEK
    EVER_NODE_ADNL_PORT: 49999
    EVER_NODE_MEMORY_LIMIT: 64G
    EVER_NODE_IMAGE: "ghcr.io/treeton-org/ever-node:eec4214efdeccdbdff8c4e671bcebec2e575d54c"

    Q_SERVER_IMAGE: "ghcr.io/treeton-org/q-server:0.55.1"

    BASIC_AUTH_USER: admin
    BASIC_AUTH_PASSWORD: admin