- name: Restart ever-node container
  hosts: all
  remote_user: root

  tasks:
    - name: Restart
      shell: docker exec ever-node "docker container restart ever-node"
      args:
        chdir: /srv/application-server