version: '3.9'
services:
  keygen:
    image: ${EVER_NODE_IMAGE}
    container_name: ever-node
    environment:
      ADNL_PORT: ${EVER_NODE_ADNL_PORT}
      VALIDATOR_NAME: "${EVER_NODE_VALIDATOR_NAME}"
      CONSOLE_SERVER_PORT: ${EVER_NODE_CONSOLE_SERVER_PORT}
      STATSD_DOMAIN: "statsd:"
      STATSD_PORT: 9125
      MEM_LIMIT: ${EVER_NODE_MEMORY_LIMIT}
    networks:
      - application
    ports:
      - "${EVER_NODE_ADNL_PORT}:${EVER_NODE_ADNL_PORT}/udp"
    volumes:
      - ./docker/ever-node/default:/ever-node/default
      - ./docker/ever-node/ton-global.config.json:/ever-node/ton-global.config.json:ro
      - ./docker/ever-node/keygen:/ever-node/keygen:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ever-node-configs:/ever-node/configs
      - ever-node-db:/ever-node/db
      - ever-node-logs:/ever-node/logs
    entrypoint: /ever-node/keygen
    cap_add:
      - SYS_PTRACE

networks:
  application:
    external: true
    name: application

volumes:
  ever-node-configs:
    external: true
  ever-node-db:
  ever-node-logs:
