name: 'Build ever-node'

on:
  workflow_dispatch:
  push:
    paths:
      - 'build/ever-node/*'
      - '.github/workflows/build-ever-node.yaml'

env:
  ORGANIZATION: treeton-org
  EVER_NODE_REPOSITORY: https://github.com/tonlabs/ever-node
  EVER_NODE_COMMIT: eec4214efdeccdbdff8c4e671bcebec2e575d54c
  EVER_NODE_TOOLS_REPOSITORY: https://github.com/tonlabs/ever-node-tools
  EVER_NODE_TOOLS_COMMIT: master

jobs:
  build:
    strategy:
      matrix:
        include:
          - features: "external_db,metrics"
            suffix: ""
          - features: "external_db,metrics,gosh"
            suffix: "-gosh"
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tags
        id: meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: ghcr.io/${{ env.ORGANIZATION }}/ever-node
          tags: |
            latest
            type=raw,value=${{ env.EVER_NODE_COMMIT }}${{ matrix.suffix }}

      - name: Build and push
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./build/ever-node
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            EVER_NODE_REPOSITORY=${{ env.EVER_NODE_REPOSITORY }}
            EVER_NODE_COMMIT=${{ env.EVER_NODE_COMMIT }}
            EVER_NODE_TOOLS_REPOSITORY=${{ env.EVER_NODE_TOOLS_REPOSITORY }}
            EVER_NODE_TOOLS_COMMIT=${{ env.EVER_NODE_TOOLS_COMMIT }}
            FEATURES=${{ matrix.features }}
