name: 'Build q-server'

on:
  workflow_dispatch:

env:
  TON_Q_SERVER_GITHUB_COMMIT_ID: 0.55.1

jobs:
  build-ever-node:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tags
        id: meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: ghcr.io/treeton-org/q-server
          tags: |
            latest
            type=raw,value=0.55.1

      - name: Build and push
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./build/q-server
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            TON_Q_SERVER_GITHUB_COMMIT_ID: ${{ env.TON_Q_SERVER_GITHUB_COMMIT_ID }}
