name: 'Build *.jar files for Kafka Connect and ArangoDB'

on:
  workflow_dispatch:
  push:
    paths:
      - 'build/kafka-connect-arangodb-jars/*'
      - '.github/workflows/build-kafka-connect-arangodb-jars.yaml'

env:
  ORGANIZATION: treeton-org
  VERSION: 1.0.0

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tags
        id: meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: ghcr.io/${{ env.ORGANIZATION }}/kafka-connect-arangodb-jars
          tags: |
            latest
            type=raw,value=${{ env.VERSION }}

      - name: Build and push
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./build/q-server
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
